//Destination Request

GET http://localhost:5500/destination

###
GET http://localhost:5500/destination/3

###
POST http://localhost:5500/destination
Content-Type: application/json

{
    "Nama_Wisata": "︎",
    "Alamat": "",
    "Biaya_Masuk": "",
    "Deskripsi": ""
}

###
PATCH http://localhost:5500/destination/2
Content-Type: application/json

{
    
}

###
DELETE http://localhost:5500/destination/2