//Destination Request

GET http://localhost:5000/destination

###
GET http://localhost:5000/destination/3

###
POST http://localhost:5000/destination
Content-Type: application/json

{
    
}

###
PATCH http://localhost:5000/destination/2
Content-Type: application/json

{
    
}

###
DELETE http://localhost:5000/destination/2
